all:
  hosts:
    node1:
      ansible_host: 10.100.129.204
      ip: 10.100.129.204
      access_ip: 10.100.129.204
    node2:
      ansible_host: 10.100.129.205
      ip: 10.100.129.205
      access_ip: 10.100.129.205
    node3:
      ansible_host: 10.100.129.206
      ip: 10.100.129.206
      access_ip: 10.100.129.206
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
